# Mandatory settings

blog_theme: light # dark or light
name: Sharynne Azhar
paginate: 8
url: https://sharynneazhar.com/


# Optional settings

about_enabled: true
baseurl: '/blog'
discus_identifier: 'blog-sharynne-azhar'
ga_analytics: 'UA-91479922-2'
local_fonts: false
rss_enabled: true
scrollappear_enabled: true
social:
  dribbble:
  facebook:
  flickr:
  github: 'sharynneazhar'
  linkedin: 'sharynneazhar'
  twitter: 'sharynneazhar'
  email: 'sharynneazhar@gmail.com'
  bitcoin:
  ethereum:
  gitlab:
  youtube:
  twitch:
  discord:
  tumblr:
  bitbucket:
  docker:
  instagram: 'heysharynne'
  keybase:
  medium: 'sharynneazhar'
  spotify:
  stackoverflow:
  steam:


# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
